---
abstract: 'GURL class implementation from the Google URL library.'
author:
  - unknown
build_requires:
  ExtUtils::Typemaps::Default: 0.01
  ExtUtils::XSpp: 0.17
configure_requires:
  Devel::CheckLib: 0.01
  ExtUtils::CppGuess: 0.07
  Module::Build: 0.40
  Module::Build::WithXSpp: 0.01
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URL-Google-GURL
provides:
  URL::Google::GURL:
    file: lib/URL/Google/GURL.pm
    version: 0.03
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
