---
abstract: 'GURL class from the Google url library.'
author:
  - unknown
build_requires:
  ExtUtils::Typemaps::Default: 0.01
  ExtUtils::XSpp: 0.16
configure_requires:
  ExtUtils::CppGuess: 0.07
  Module::Build: 0.38
  Module::Build::WithXSpp: 0.10
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URL-Google-GURL
provides:
  URL::Google::GURL:
    file: lib/URL/Google/GURL.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
